import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCar = {
  slug: string;
  name: string;
  priceMinLakh: number;
  priceMaxLakh: number;
  fuelType: string;
  segment: string;
  transmission: string;
  seats: number;
  sunroof: boolean;
  safetyRating: number | null;
  avgRating: number | null;
  reviewSummary: string | null;
};

const cars: SeedCar[] = [
  {
    slug: "maruti-swift-vxi",
    name: "Maruti Swift VXI",
    priceMinLakh: 6.5,
    priceMaxLakh: 8.2,
    fuelType: "PETROL",
    segment: "HATCHBACK",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.2,
    reviewSummary: "Fun to drive hatch; tight rear seat.",
  },
  {
    slug: "maruti-baleno-delta",
    name: "Maruti Baleno Delta",
    priceMinLakh: 7.0,
    priceMaxLakh: 9.0,
    fuelType: "PETROL",
    segment: "HATCHBACK",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.0,
    reviewSummary: "Spacious for segment; light steering.",
  },
  {
    slug: "hyundai-i20-sportz",
    name: "Hyundai i20 Sportz",
    priceMinLakh: 7.8,
    priceMaxLakh: 10.0,
    fuelType: "PETROL",
    segment: "HATCHBACK",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.3,
    reviewSummary: "Premium feel; good features list.",
  },
  {
    slug: "tata-altroz-xz",
    name: "Tata Altroz XZ",
    priceMinLakh: 7.5,
    priceMaxLakh: 9.5,
    fuelType: "PETROL",
    segment: "HATCHBACK",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 5,
    avgRating: 4.1,
    reviewSummary: "Strong safety story; diesel option popular.",
  },
  {
    slug: "tata-punch-creative",
    name: "Tata Punch Creative",
    priceMinLakh: 6.8,
    priceMaxLakh: 8.8,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 5,
    avgRating: 4.4,
    reviewSummary: "Compact SUV stance; good ground clearance.",
  },
  {
    slug: "hyundai-venue-sx",
    name: "Hyundai Venue SX",
    priceMinLakh: 9.0,
    priceMaxLakh: 11.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.0,
    reviewSummary: "City friendly; turbo option fun.",
  },
  {
    slug: "kia-sonet-htk-plus",
    name: "Kia Sonet HTK+",
    priceMinLakh: 9.5,
    priceMaxLakh: 12.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.2,
    reviewSummary: "Feature packed; rear space average.",
  },
  {
    slug: "kia-sonet-gtx-dct",
    name: "Kia Sonet GTX+ DCT",
    priceMinLakh: 12.0,
    priceMaxLakh: 14.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.5,
    reviewSummary: "Quick DCT; sunroof on top trims.",
  },
  {
    slug: "hyundai-creta-sx",
    name: "Hyundai Creta SX",
    priceMinLakh: 13.0,
    priceMaxLakh: 16.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.4,
    reviewSummary: "All-rounder midsize SUV.",
  },
  {
    slug: "hyundai-creta-sx-o-dct",
    name: "Hyundai Creta SX(O) DCT",
    priceMinLakh: 16.0,
    priceMaxLakh: 19.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.5,
    reviewSummary: "Smooth DCT; highway comfort.",
  },
  {
    slug: "kia-seltos-gtx",
    name: "Kia Seltos GTX",
    priceMinLakh: 15.0,
    priceMaxLakh: 18.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.3,
    reviewSummary: "Sporty tune; ADAS on higher trims.",
  },
  {
    slug: "mg-hector-sharp",
    name: "MG Hector Sharp",
    priceMinLakh: 16.5,
    priceMaxLakh: 21.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.0,
    reviewSummary: "Large cabin; infotainment heavy.",
  },
  {
    slug: "tata-harrier-pure",
    name: "Tata Harrier Pure",
    priceMinLakh: 15.5,
    priceMaxLakh: 19.0,
    fuelType: "DIESEL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 5,
    avgRating: 4.4,
    reviewSummary: "Diesel torque; solid ride.",
  },
  {
    slug: "tata-safari-adventure",
    name: "Tata Safari Adventure",
    priceMinLakh: 18.0,
    priceMaxLakh: 24.0,
    fuelType: "DIESEL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 7,
    sunroof: true,
    safetyRating: 5,
    avgRating: 4.3,
    reviewSummary: "Three rows; highway cruiser.",
  },
  {
    slug: "mahindra-xuv700-ax7",
    name: "Mahindra XUV700 AX7",
    priceMinLakh: 20.0,
    priceMaxLakh: 26.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 7,
    sunroof: true,
    safetyRating: 5,
    avgRating: 4.5,
    reviewSummary: "Powerful petrol; tech-forward cabin.",
  },
  {
    slug: "toyota-hyryder-s",
    name: "Toyota Urban Cruiser Hyryder S",
    priceMinLakh: 12.5,
    priceMaxLakh: 15.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.1,
    reviewSummary: "Toyota reliability; hybrid on higher trims.",
  },
  {
    slug: "maruti-ertiga-zxi",
    name: "Maruti Ertiga ZXI",
    priceMinLakh: 10.5,
    priceMaxLakh: 13.0,
    fuelType: "PETROL",
    segment: "MPV",
    transmission: "MANUAL",
    seats: 7,
    sunroof: false,
    safetyRating: 3,
    avgRating: 4.0,
    reviewSummary: "Practical MPV; light controls.",
  },
  {
    slug: "kia-carens-prestige",
    name: "Kia Carens Prestige",
    priceMinLakh: 12.0,
    priceMaxLakh: 15.5,
    fuelType: "PETROL",
    segment: "MPV",
    transmission: "MANUAL",
    seats: 7,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.2,
    reviewSummary: "Crossover MPV styling.",
  },
  {
    slug: "honda-city-vx",
    name: "Honda City VX",
    priceMinLakh: 12.0,
    priceMaxLakh: 14.5,
    fuelType: "PETROL",
    segment: "SEDAN",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.4,
    reviewSummary: "Refined petrol; rear legroom strong.",
  },
  {
    slug: "honda-city-v-cvt",
    name: "Honda City V CVT",
    priceMinLakh: 13.5,
    priceMaxLakh: 16.0,
    fuelType: "PETROL",
    segment: "SEDAN",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.5,
    reviewSummary: "CVT smoothness for city traffic.",
  },
  {
    slug: "skoda-slavia-style",
    name: "Skoda Slavia Style",
    priceMinLakh: 13.0,
    priceMaxLakh: 16.5,
    fuelType: "PETROL",
    segment: "SEDAN",
    transmission: "MANUAL",
    seats: 5,
    sunroof: true,
    safetyRating: 5,
    avgRating: 4.3,
    reviewSummary: "Solid build; turbo fun.",
  },
  {
    slug: "vw-virtus-sound-edition",
    name: "VW Virtus Sound Edition",
    priceMinLakh: 14.0,
    priceMaxLakh: 17.5,
    fuelType: "PETROL",
    segment: "SEDAN",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 5,
    avgRating: 4.2,
    reviewSummary: "GT tune available; firm ride.",
  },
  {
    slug: "tata-tigor-xz-cng",
    name: "Tata Tigor XZ CNG",
    priceMinLakh: 7.2,
    priceMaxLakh: 8.8,
    fuelType: "CNG",
    segment: "SEDAN",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 3.9,
    reviewSummary: "Factory CNG; compact sedan.",
  },
  {
    slug: "tata-nexon-ev-prime",
    name: "Tata Nexon EV Prime",
    priceMinLakh: 14.5,
    priceMaxLakh: 17.5,
    fuelType: "EV",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: false,
    safetyRating: 5,
    avgRating: 4.3,
    reviewSummary: "Popular EV; city range solid.",
  },
  {
    slug: "mg-zs-ev-excite",
    name: "MG ZS EV Excite",
    priceMinLakh: 15.0,
    priceMaxLakh: 18.0,
    fuelType: "EV",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 4,
    avgRating: 4.0,
    reviewSummary: "Spacious EV; charging curve ok.",
  },
  {
    slug: "byd-atto-3",
    name: "BYD Atto 3",
    priceMinLakh: 24.0,
    priceMaxLakh: 28.0,
    fuelType: "EV",
    segment: "SUV",
    transmission: "AUTOMATIC",
    seats: 5,
    sunroof: true,
    safetyRating: 5,
    avgRating: 4.4,
    reviewSummary: "Blade battery; quirky interior.",
  },
  {
    slug: "maruti-fronx-delta-turbo",
    name: "Maruti Fronx Delta Turbo",
    priceMinLakh: 8.5,
    priceMaxLakh: 10.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 3,
    avgRating: 4.1,
    reviewSummary: "Boosterjet pep; coupe-crossover look.",
  },
  {
    slug: "renault-kiger-rxt",
    name: "Renault Kiger RXT",
    priceMinLakh: 7.0,
    priceMaxLakh: 9.0,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 3,
    avgRating: 3.8,
    reviewSummary: "Value SUV; plastics hard.",
  },
  {
    slug: "nissan-magnite-turbo",
    name: "Nissan Magnite Turbo",
    priceMinLakh: 7.5,
    priceMaxLakh: 9.8,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 3,
    avgRating: 3.9,
    reviewSummary: "Turbo value; rear seat tight.",
  },
  {
    slug: "honda-elevate-vx",
    name: "Honda Elevate VX",
    priceMinLakh: 12.0,
    priceMaxLakh: 14.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: 4,
    avgRating: 4.2,
    reviewSummary: "Honda refinement in compact SUV.",
  },
  {
    slug: "citroen-c3-aircross-max",
    name: "Citroen C3 Aircross Max",
    priceMinLakh: 11.0,
    priceMaxLakh: 13.5,
    fuelType: "PETROL",
    segment: "SUV",
    transmission: "MANUAL",
    seats: 7,
    sunroof: false,
    safetyRating: 3,
    avgRating: 3.9,
    reviewSummary: "Comfort suspension; third row usable.",
  },
  {
    slug: "unknown-rating-sedan",
    name: "Budget Sedan X (synthetic)",
    priceMinLakh: 5.5,
    priceMaxLakh: 6.5,
    fuelType: "PETROL",
    segment: "SEDAN",
    transmission: "MANUAL",
    seats: 5,
    sunroof: false,
    safetyRating: null,
    avgRating: null,
    reviewSummary: null,
  },
];

async function main() {
  for (const car of cars) {
    await prisma.car.upsert({
      where: { slug: car.slug },
      create: car,
      update: car,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
